//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JPath.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BuildXL.Execution.Analyzer.JPath {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class JPathParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, WS=14, NOT=15, AND=16, OR=17, XOR=18, 
		IFF=19, GTE=20, LTE=21, GT=22, LT=23, EQ=24, NEQ=25, MATCH=26, NMATCH=27, 
		MINUS=28, PLUS=29, TIMES=30, DIV=31, MOD=32, CONCAT=33, INTERSECT=34, 
		IntLit=35, StrLit=36, RegExLit=37, VarID=38, RootID=39, ESC_ID=40;
	public const int
		RULE_intBinaryOp = 0, RULE_intUnaryOp = 1, RULE_boolBinaryOp = 2, RULE_logicBinaryOp = 3, 
		RULE_logicUnaryOp = 4, RULE_arrayBinaryOp = 5, RULE_anyBinaryOp = 6, RULE_intExpr = 7, 
		RULE_boolExpr = 8, RULE_logicExpr = 9, RULE_id = 10, RULE_selector = 11, 
		RULE_expr = 12;
	public static readonly string[] ruleNames = {
		"intBinaryOp", "intUnaryOp", "boolBinaryOp", "logicBinaryOp", "logicUnaryOp", 
		"arrayBinaryOp", "anyBinaryOp", "intExpr", "boolExpr", "logicExpr", "id", 
		"selector", "expr"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'$'", "'.'", "'['", "']'", "'..'", "'#'", "','", 
		"'|'", "'let'", "':='", "'in'", null, "'not'", "'and'", "'or'", "'xor'", 
		"'iff'", "'>='", "'<='", "'>'", "'<'", "'='", "'!='", "'~'", "'!~'", "'-'", 
		"'+'", "'*'", "'/'", "'%'", "'++'", "'&'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "WS", "NOT", "AND", "OR", "XOR", "IFF", "GTE", "LTE", "GT", 
		"LT", "EQ", "NEQ", "MATCH", "NMATCH", "MINUS", "PLUS", "TIMES", "DIV", 
		"MOD", "CONCAT", "INTERSECT", "IntLit", "StrLit", "RegExLit", "VarID", 
		"RootID", "ESC_ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JPath.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static JPathParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public JPathParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public JPathParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class IntBinaryOpContext : ParserRuleContext {
		public IToken Token;
		public ITerminalNode PLUS() { return GetToken(JPathParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(JPathParser.MINUS, 0); }
		public ITerminalNode TIMES() { return GetToken(JPathParser.TIMES, 0); }
		public ITerminalNode DIV() { return GetToken(JPathParser.DIV, 0); }
		public ITerminalNode MOD() { return GetToken(JPathParser.MOD, 0); }
		public IntBinaryOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_intBinaryOp; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterIntBinaryOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitIntBinaryOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntBinaryOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntBinaryOpContext intBinaryOp() {
		IntBinaryOpContext _localctx = new IntBinaryOpContext(Context, State);
		EnterRule(_localctx, 0, RULE_intBinaryOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 26;
			_localctx.Token = TokenStream.LT(1);
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MINUS) | (1L << PLUS) | (1L << TIMES) | (1L << DIV) | (1L << MOD))) != 0)) ) {
				_localctx.Token = ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IntUnaryOpContext : ParserRuleContext {
		public IToken Token;
		public ITerminalNode MINUS() { return GetToken(JPathParser.MINUS, 0); }
		public IntUnaryOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_intUnaryOp; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterIntUnaryOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitIntUnaryOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntUnaryOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntUnaryOpContext intUnaryOp() {
		IntUnaryOpContext _localctx = new IntUnaryOpContext(Context, State);
		EnterRule(_localctx, 2, RULE_intUnaryOp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 28; _localctx.Token = Match(MINUS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BoolBinaryOpContext : ParserRuleContext {
		public IToken Token;
		public ITerminalNode GTE() { return GetToken(JPathParser.GTE, 0); }
		public ITerminalNode GT() { return GetToken(JPathParser.GT, 0); }
		public ITerminalNode LTE() { return GetToken(JPathParser.LTE, 0); }
		public ITerminalNode LT() { return GetToken(JPathParser.LT, 0); }
		public ITerminalNode EQ() { return GetToken(JPathParser.EQ, 0); }
		public ITerminalNode NEQ() { return GetToken(JPathParser.NEQ, 0); }
		public ITerminalNode MATCH() { return GetToken(JPathParser.MATCH, 0); }
		public ITerminalNode NMATCH() { return GetToken(JPathParser.NMATCH, 0); }
		public BoolBinaryOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_boolBinaryOp; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterBoolBinaryOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitBoolBinaryOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolBinaryOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BoolBinaryOpContext boolBinaryOp() {
		BoolBinaryOpContext _localctx = new BoolBinaryOpContext(Context, State);
		EnterRule(_localctx, 4, RULE_boolBinaryOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 30;
			_localctx.Token = TokenStream.LT(1);
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << GTE) | (1L << LTE) | (1L << GT) | (1L << LT) | (1L << EQ) | (1L << NEQ) | (1L << MATCH) | (1L << NMATCH))) != 0)) ) {
				_localctx.Token = ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicBinaryOpContext : ParserRuleContext {
		public IToken Token;
		public ITerminalNode AND() { return GetToken(JPathParser.AND, 0); }
		public ITerminalNode OR() { return GetToken(JPathParser.OR, 0); }
		public ITerminalNode XOR() { return GetToken(JPathParser.XOR, 0); }
		public ITerminalNode IFF() { return GetToken(JPathParser.IFF, 0); }
		public LogicBinaryOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicBinaryOp; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterLogicBinaryOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitLogicBinaryOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicBinaryOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicBinaryOpContext logicBinaryOp() {
		LogicBinaryOpContext _localctx = new LogicBinaryOpContext(Context, State);
		EnterRule(_localctx, 6, RULE_logicBinaryOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32;
			_localctx.Token = TokenStream.LT(1);
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << AND) | (1L << OR) | (1L << XOR) | (1L << IFF))) != 0)) ) {
				_localctx.Token = ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicUnaryOpContext : ParserRuleContext {
		public IToken Token;
		public ITerminalNode NOT() { return GetToken(JPathParser.NOT, 0); }
		public LogicUnaryOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicUnaryOp; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterLogicUnaryOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitLogicUnaryOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicUnaryOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicUnaryOpContext logicUnaryOp() {
		LogicUnaryOpContext _localctx = new LogicUnaryOpContext(Context, State);
		EnterRule(_localctx, 8, RULE_logicUnaryOp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 34; _localctx.Token = Match(NOT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayBinaryOpContext : ParserRuleContext {
		public IToken Token;
		public ITerminalNode CONCAT() { return GetToken(JPathParser.CONCAT, 0); }
		public ITerminalNode INTERSECT() { return GetToken(JPathParser.INTERSECT, 0); }
		public ArrayBinaryOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayBinaryOp; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterArrayBinaryOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitArrayBinaryOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayBinaryOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayBinaryOpContext arrayBinaryOp() {
		ArrayBinaryOpContext _localctx = new ArrayBinaryOpContext(Context, State);
		EnterRule(_localctx, 10, RULE_arrayBinaryOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36;
			_localctx.Token = TokenStream.LT(1);
			_la = TokenStream.LA(1);
			if ( !(_la==CONCAT || _la==INTERSECT) ) {
				_localctx.Token = ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AnyBinaryOpContext : ParserRuleContext {
		public IntBinaryOpContext intBinaryOp() {
			return GetRuleContext<IntBinaryOpContext>(0);
		}
		public BoolBinaryOpContext boolBinaryOp() {
			return GetRuleContext<BoolBinaryOpContext>(0);
		}
		public LogicBinaryOpContext logicBinaryOp() {
			return GetRuleContext<LogicBinaryOpContext>(0);
		}
		public ArrayBinaryOpContext arrayBinaryOp() {
			return GetRuleContext<ArrayBinaryOpContext>(0);
		}
		public AnyBinaryOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_anyBinaryOp; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterAnyBinaryOp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitAnyBinaryOp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAnyBinaryOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AnyBinaryOpContext anyBinaryOp() {
		AnyBinaryOpContext _localctx = new AnyBinaryOpContext(Context, State);
		EnterRule(_localctx, 12, RULE_anyBinaryOp);
		try {
			State = 42;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case MINUS:
			case PLUS:
			case TIMES:
			case DIV:
			case MOD:
				EnterOuterAlt(_localctx, 1);
				{
				State = 38; intBinaryOp();
				}
				break;
			case GTE:
			case LTE:
			case GT:
			case LT:
			case EQ:
			case NEQ:
			case MATCH:
			case NMATCH:
				EnterOuterAlt(_localctx, 2);
				{
				State = 39; boolBinaryOp();
				}
				break;
			case AND:
			case OR:
			case XOR:
			case IFF:
				EnterOuterAlt(_localctx, 3);
				{
				State = 40; logicBinaryOp();
				}
				break;
			case CONCAT:
			case INTERSECT:
				EnterOuterAlt(_localctx, 4);
				{
				State = 41; arrayBinaryOp();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IntExprContext : ParserRuleContext {
		public IntExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_intExpr; } }
	 
		public IntExprContext() { }
		public virtual void CopyFrom(IntExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class BinaryIntExprContext : IntExprContext {
		public IntExprContext Lhs;
		public IntBinaryOpContext Op;
		public IntExprContext Rhs;
		public IntExprContext[] intExpr() {
			return GetRuleContexts<IntExprContext>();
		}
		public IntExprContext intExpr(int i) {
			return GetRuleContext<IntExprContext>(i);
		}
		public IntBinaryOpContext intBinaryOp() {
			return GetRuleContext<IntBinaryOpContext>(0);
		}
		public BinaryIntExprContext(IntExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterBinaryIntExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitBinaryIntExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryIntExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExprIntExprContext : IntExprContext {
		public ExprContext Expr;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ExprIntExprContext(IntExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterExprIntExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitExprIntExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprIntExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryIntExprContext : IntExprContext {
		public IntUnaryOpContext Op;
		public IntExprContext Sub;
		public IntUnaryOpContext intUnaryOp() {
			return GetRuleContext<IntUnaryOpContext>(0);
		}
		public IntExprContext intExpr() {
			return GetRuleContext<IntExprContext>(0);
		}
		public UnaryIntExprContext(IntExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterUnaryIntExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitUnaryIntExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryIntExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SubIntExprContext : IntExprContext {
		public IntExprContext Sub;
		public IntExprContext intExpr() {
			return GetRuleContext<IntExprContext>(0);
		}
		public SubIntExprContext(IntExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterSubIntExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitSubIntExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubIntExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntExprContext intExpr() {
		return intExpr(0);
	}

	private IntExprContext intExpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		IntExprContext _localctx = new IntExprContext(Context, _parentState);
		IntExprContext _prevctx = _localctx;
		int _startState = 14;
		EnterRecursionRule(_localctx, 14, RULE_intExpr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				{
				_localctx = new ExprIntExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 45; ((ExprIntExprContext)_localctx).Expr = expr(0);
				}
				break;
			case 2:
				{
				_localctx = new UnaryIntExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 46; ((UnaryIntExprContext)_localctx).Op = intUnaryOp();
				State = 47; ((UnaryIntExprContext)_localctx).Sub = intExpr(3);
				}
				break;
			case 3:
				{
				_localctx = new SubIntExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 49; Match(T__0);
				State = 50; ((SubIntExprContext)_localctx).Sub = intExpr(0);
				State = 51; Match(T__1);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 61;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new BinaryIntExprContext(new IntExprContext(_parentctx, _parentState));
					((BinaryIntExprContext)_localctx).Lhs = _prevctx;
					PushNewRecursionContext(_localctx, _startState, RULE_intExpr);
					State = 55;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 56; ((BinaryIntExprContext)_localctx).Op = intBinaryOp();
					State = 57; ((BinaryIntExprContext)_localctx).Rhs = intExpr(3);
					}
					} 
				}
				State = 63;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class BoolExprContext : ParserRuleContext {
		public BoolExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_boolExpr; } }
	 
		public BoolExprContext() { }
		public virtual void CopyFrom(BoolExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class BinaryBoolExprContext : BoolExprContext {
		public IntExprContext Lhs;
		public BoolBinaryOpContext Op;
		public IntExprContext Rhs;
		public IntExprContext[] intExpr() {
			return GetRuleContexts<IntExprContext>();
		}
		public IntExprContext intExpr(int i) {
			return GetRuleContext<IntExprContext>(i);
		}
		public BoolBinaryOpContext boolBinaryOp() {
			return GetRuleContext<BoolBinaryOpContext>(0);
		}
		public BinaryBoolExprContext(BoolExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterBinaryBoolExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitBinaryBoolExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryBoolExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SubBoolExprContext : BoolExprContext {
		public BoolExprContext Sub;
		public BoolExprContext boolExpr() {
			return GetRuleContext<BoolExprContext>(0);
		}
		public SubBoolExprContext(BoolExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterSubBoolExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitSubBoolExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubBoolExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BoolExprContext boolExpr() {
		BoolExprContext _localctx = new BoolExprContext(Context, State);
		EnterRule(_localctx, 16, RULE_boolExpr);
		try {
			State = 72;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				_localctx = new BinaryBoolExprContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 64; ((BinaryBoolExprContext)_localctx).Lhs = intExpr(0);
				State = 65; ((BinaryBoolExprContext)_localctx).Op = boolBinaryOp();
				State = 66; ((BinaryBoolExprContext)_localctx).Rhs = intExpr(0);
				}
				break;
			case 2:
				_localctx = new SubBoolExprContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 68; Match(T__0);
				State = 69; ((SubBoolExprContext)_localctx).Sub = boolExpr();
				State = 70; Match(T__1);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicExprContext : ParserRuleContext {
		public LogicExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicExpr; } }
	 
		public LogicExprContext() { }
		public virtual void CopyFrom(LogicExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class BoolLogicExprContext : LogicExprContext {
		public BoolExprContext Expr;
		public BoolExprContext boolExpr() {
			return GetRuleContext<BoolExprContext>(0);
		}
		public BoolLogicExprContext(LogicExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterBoolLogicExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitBoolLogicExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolLogicExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryLogicExprContext : LogicExprContext {
		public LogicUnaryOpContext Op;
		public LogicExprContext Sub;
		public LogicUnaryOpContext logicUnaryOp() {
			return GetRuleContext<LogicUnaryOpContext>(0);
		}
		public LogicExprContext logicExpr() {
			return GetRuleContext<LogicExprContext>(0);
		}
		public UnaryLogicExprContext(LogicExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterUnaryLogicExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitUnaryLogicExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryLogicExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SubLogicExprContext : LogicExprContext {
		public LogicExprContext Sub;
		public LogicExprContext logicExpr() {
			return GetRuleContext<LogicExprContext>(0);
		}
		public SubLogicExprContext(LogicExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterSubLogicExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitSubLogicExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubLogicExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinaryLogicExprContext : LogicExprContext {
		public LogicExprContext Lhs;
		public LogicBinaryOpContext Op;
		public LogicExprContext Rhs;
		public LogicExprContext[] logicExpr() {
			return GetRuleContexts<LogicExprContext>();
		}
		public LogicExprContext logicExpr(int i) {
			return GetRuleContext<LogicExprContext>(i);
		}
		public LogicBinaryOpContext logicBinaryOp() {
			return GetRuleContext<LogicBinaryOpContext>(0);
		}
		public BinaryLogicExprContext(LogicExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterBinaryLogicExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitBinaryLogicExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryLogicExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicExprContext logicExpr() {
		return logicExpr(0);
	}

	private LogicExprContext logicExpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		LogicExprContext _localctx = new LogicExprContext(Context, _parentState);
		LogicExprContext _prevctx = _localctx;
		int _startState = 18;
		EnterRecursionRule(_localctx, 18, RULE_logicExpr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				{
				_localctx = new BoolLogicExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 75; ((BoolLogicExprContext)_localctx).Expr = boolExpr();
				}
				break;
			case 2:
				{
				_localctx = new UnaryLogicExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 76; ((UnaryLogicExprContext)_localctx).Op = logicUnaryOp();
				State = 77; ((UnaryLogicExprContext)_localctx).Sub = logicExpr(2);
				}
				break;
			case 3:
				{
				_localctx = new SubLogicExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 79; Match(T__0);
				State = 80; ((SubLogicExprContext)_localctx).Sub = logicExpr(0);
				State = 81; Match(T__1);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 91;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new BinaryLogicExprContext(new LogicExprContext(_parentctx, _parentState));
					((BinaryLogicExprContext)_localctx).Lhs = _prevctx;
					PushNewRecursionContext(_localctx, _startState, RULE_logicExpr);
					State = 85;
					if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
					State = 86; ((BinaryLogicExprContext)_localctx).Op = logicBinaryOp();
					State = 87; ((BinaryLogicExprContext)_localctx).Rhs = logicExpr(4);
					}
					} 
				}
				State = 93;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class IdContext : ParserRuleContext {
		public IdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_id; } }
	 
		public IdContext() { }
		public virtual void CopyFrom(IdContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class EscIdSelectorContext : IdContext {
		public IToken PropertyName;
		public ITerminalNode ESC_ID() { return GetToken(JPathParser.ESC_ID, 0); }
		public EscIdSelectorContext(IdContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterEscIdSelector(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitEscIdSelector(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEscIdSelector(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdSelectorContext : IdContext {
		public IToken PropertyName;
		public ITerminalNode VarID() { return GetToken(JPathParser.VarID, 0); }
		public IdSelectorContext(IdContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterIdSelector(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitIdSelector(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdSelector(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdContext id() {
		IdContext _localctx = new IdContext(Context, State);
		EnterRule(_localctx, 20, RULE_id);
		try {
			State = 96;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VarID:
				_localctx = new IdSelectorContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 94; ((IdSelectorContext)_localctx).PropertyName = Match(VarID);
				}
				break;
			case ESC_ID:
				_localctx = new EscIdSelectorContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 95; ((EscIdSelectorContext)_localctx).PropertyName = Match(ESC_ID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectorContext : ParserRuleContext {
		public SelectorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selector; } }
	 
		public SelectorContext() { }
		public virtual void CopyFrom(SelectorContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class RootIdSelectorContext : SelectorContext {
		public IToken RootPropertyName;
		public ITerminalNode RootID() { return GetToken(JPathParser.RootID, 0); }
		public RootIdSelectorContext(SelectorContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterRootIdSelector(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitRootIdSelector(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRootIdSelector(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NameSelectorContext : SelectorContext {
		public IdContext Name;
		public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public NameSelectorContext(SelectorContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterNameSelector(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitNameSelector(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNameSelector(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnionSelectorContext : SelectorContext {
		public IdContext _id;
		public IList<IdContext> _Names = new List<IdContext>();
		public IdContext[] id() {
			return GetRuleContexts<IdContext>();
		}
		public IdContext id(int i) {
			return GetRuleContext<IdContext>(i);
		}
		public ITerminalNode[] PLUS() { return GetTokens(JPathParser.PLUS); }
		public ITerminalNode PLUS(int i) {
			return GetToken(JPathParser.PLUS, i);
		}
		public UnionSelectorContext(SelectorContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterUnionSelector(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitUnionSelector(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnionSelector(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectorContext selector() {
		SelectorContext _localctx = new SelectorContext(Context, State);
		EnterRule(_localctx, 22, RULE_selector);
		int _la;
		try {
			State = 110;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VarID:
			case ESC_ID:
				_localctx = new NameSelectorContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 98; ((NameSelectorContext)_localctx).Name = id();
				}
				break;
			case RootID:
				_localctx = new RootIdSelectorContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 99; ((RootIdSelectorContext)_localctx).RootPropertyName = Match(RootID);
				}
				break;
			case T__0:
				_localctx = new UnionSelectorContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 100; Match(T__0);
				State = 101; ((UnionSelectorContext)_localctx)._id = id();
				((UnionSelectorContext)_localctx)._Names.Add(((UnionSelectorContext)_localctx)._id);
				State = 104;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 102; Match(PLUS);
					State = 103; ((UnionSelectorContext)_localctx)._id = id();
					((UnionSelectorContext)_localctx)._Names.Add(((UnionSelectorContext)_localctx)._id);
					}
					}
					State = 106;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==PLUS );
				State = 108; Match(T__1);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class MapExprContext : ExprContext {
		public ExprContext Lhs;
		public SelectorContext Selector;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public MapExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterMapExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitMapExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMapExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CardinalityExprContext : ExprContext {
		public ExprContext Sub;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public CardinalityExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterCardinalityExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitCardinalityExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCardinalityExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LetExprContext : ExprContext {
		public IdContext Name;
		public ExprContext Bnd;
		public ExprContext Sub;
		public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public LetExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterLetExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitLetExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLetExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncAppExprContext : ExprContext {
		public ExprContext Func;
		public ExprContext _expr;
		public IList<ExprContext> _Args = new List<ExprContext>();
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public FuncAppExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterFuncAppExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitFuncAppExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncAppExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SubExprContext : ExprContext {
		public ExprContext Sub;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public SubExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterSubExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitSubExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinExprContext : ExprContext {
		public ExprContext Lhs;
		public AnyBinaryOpContext Op;
		public ExprContext Rhs;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public AnyBinaryOpContext anyBinaryOp() {
			return GetRuleContext<AnyBinaryOpContext>(0);
		}
		public BinExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterBinExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitBinExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RangeExprContext : ExprContext {
		public ExprContext Lhs;
		public IntExprContext Begin;
		public IntExprContext End;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public IntExprContext[] intExpr() {
			return GetRuleContexts<IntExprContext>();
		}
		public IntExprContext intExpr(int i) {
			return GetRuleContext<IntExprContext>(i);
		}
		public RangeExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterRangeExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitRangeExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRangeExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IndexExprContext : ExprContext {
		public ExprContext Lhs;
		public IntExprContext Index;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public IntExprContext intExpr() {
			return GetRuleContext<IntExprContext>(0);
		}
		public IndexExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterIndexExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitIndexExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIndexExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RegExLitExprContext : ExprContext {
		public IToken Value;
		public ITerminalNode RegExLit() { return GetToken(JPathParser.RegExLit, 0); }
		public RegExLitExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterRegExLitExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitRegExLitExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRegExLitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SelectorExprContext : ExprContext {
		public SelectorContext Sub;
		public SelectorContext selector() {
			return GetRuleContext<SelectorContext>(0);
		}
		public SelectorExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterSelectorExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitSelectorExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelectorExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FilterExprContext : ExprContext {
		public ExprContext Lhs;
		public LogicExprContext Filter;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public LogicExprContext logicExpr() {
			return GetRuleContext<LogicExprContext>(0);
		}
		public FilterExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterFilterExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitFilterExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFilterExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RootExprContext : ExprContext {
		public RootExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterRootExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitRootExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRootExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntLitExprContext : ExprContext {
		public IToken Value;
		public ITerminalNode IntLit() { return GetToken(JPathParser.IntLit, 0); }
		public IntLitExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterIntLitExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitIntLitExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntLitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PipeExprContext : ExprContext {
		public ExprContext Input;
		public ExprContext Func;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public PipeExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterPipeExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitPipeExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPipeExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StrLitExprContext : ExprContext {
		public IToken Value;
		public ITerminalNode StrLit() { return GetToken(JPathParser.StrLit, 0); }
		public StrLitExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.EnterStrLitExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJPathListener typedListener = listener as IJPathListener;
			if (typedListener != null) typedListener.ExitStrLitExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJPathVisitor<TResult> typedVisitor = visitor as IJPathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStrLitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 24;
		EnterRecursionRule(_localctx, 24, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 132;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				_localctx = new RootExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 113; Match(T__2);
				}
				break;
			case 2:
				{
				_localctx = new SelectorExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 114; ((SelectorExprContext)_localctx).Sub = selector();
				}
				break;
			case 3:
				{
				_localctx = new StrLitExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 115; ((StrLitExprContext)_localctx).Value = Match(StrLit);
				}
				break;
			case 4:
				{
				_localctx = new RegExLitExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 116; ((RegExLitExprContext)_localctx).Value = Match(RegExLit);
				}
				break;
			case 5:
				{
				_localctx = new IntLitExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 117; ((IntLitExprContext)_localctx).Value = Match(IntLit);
				}
				break;
			case 6:
				{
				_localctx = new CardinalityExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 118; Match(T__7);
				State = 119; ((CardinalityExprContext)_localctx).Sub = expr(6);
				}
				break;
			case 7:
				{
				_localctx = new SubExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 120; Match(T__0);
				State = 121; ((SubExprContext)_localctx).Sub = expr(0);
				State = 122; Match(T__1);
				}
				break;
			case 8:
				{
				_localctx = new LetExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 124; Match(T__10);
				State = 125; ((LetExprContext)_localctx).Name = id();
				State = 126; Match(T__11);
				State = 127; ((LetExprContext)_localctx).Bnd = expr(0);
				State = 130;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
				case 1:
					{
					State = 128; Match(T__12);
					State = 129; ((LetExprContext)_localctx).Sub = expr(0);
					}
					break;
				}
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 175;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 173;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
					case 1:
						{
						_localctx = new PipeExprContext(new ExprContext(_parentctx, _parentState));
						((PipeExprContext)_localctx).Input = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 134;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 135; Match(T__9);
						State = 136; ((PipeExprContext)_localctx).Func = expr(5);
						}
						break;
					case 2:
						{
						_localctx = new BinExprContext(new ExprContext(_parentctx, _parentState));
						((BinExprContext)_localctx).Lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 137;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 138; ((BinExprContext)_localctx).Op = anyBinaryOp();
						State = 139; ((BinExprContext)_localctx).Rhs = expr(4);
						}
						break;
					case 3:
						{
						_localctx = new MapExprContext(new ExprContext(_parentctx, _parentState));
						((MapExprContext)_localctx).Lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 141;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 142; Match(T__3);
						State = 143; ((MapExprContext)_localctx).Selector = selector();
						}
						break;
					case 4:
						{
						_localctx = new FilterExprContext(new ExprContext(_parentctx, _parentState));
						((FilterExprContext)_localctx).Lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 144;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 145; Match(T__4);
						State = 146; ((FilterExprContext)_localctx).Filter = logicExpr(0);
						State = 147; Match(T__5);
						}
						break;
					case 5:
						{
						_localctx = new IndexExprContext(new ExprContext(_parentctx, _parentState));
						((IndexExprContext)_localctx).Lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 149;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 150; Match(T__4);
						State = 151; ((IndexExprContext)_localctx).Index = intExpr(0);
						State = 152; Match(T__5);
						}
						break;
					case 6:
						{
						_localctx = new RangeExprContext(new ExprContext(_parentctx, _parentState));
						((RangeExprContext)_localctx).Lhs = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 154;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 155; Match(T__4);
						State = 156; ((RangeExprContext)_localctx).Begin = intExpr(0);
						State = 157; Match(T__6);
						State = 158; ((RangeExprContext)_localctx).End = intExpr(0);
						State = 159; Match(T__5);
						}
						break;
					case 7:
						{
						_localctx = new FuncAppExprContext(new ExprContext(_parentctx, _parentState));
						((FuncAppExprContext)_localctx).Func = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 161;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 162; Match(T__0);
						State = 163; ((FuncAppExprContext)_localctx)._expr = expr(0);
						((FuncAppExprContext)_localctx)._Args.Add(((FuncAppExprContext)_localctx)._expr);
						State = 168;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						while (_la==T__8) {
							{
							{
							State = 164; Match(T__8);
							State = 165; ((FuncAppExprContext)_localctx)._expr = expr(0);
							((FuncAppExprContext)_localctx)._Args.Add(((FuncAppExprContext)_localctx)._expr);
							}
							}
							State = 170;
							ErrorHandler.Sync(this);
							_la = TokenStream.LA(1);
						}
						State = 171; Match(T__1);
						}
						break;
					}
					} 
				}
				State = 177;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 7: return intExpr_sempred((IntExprContext)_localctx, predIndex);
		case 9: return logicExpr_sempred((LogicExprContext)_localctx, predIndex);
		case 12: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool intExpr_sempred(IntExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 2);
		}
		return true;
	}
	private bool logicExpr_sempred(LogicExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 1: return Precpred(Context, 3);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 2: return Precpred(Context, 4);
		case 3: return Precpred(Context, 3);
		case 4: return Precpred(Context, 10);
		case 5: return Precpred(Context, 9);
		case 6: return Precpred(Context, 8);
		case 7: return Precpred(Context, 7);
		case 8: return Precpred(Context, 5);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '*', '\xB5', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x5', '\b', '-', '\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x5', '\t', '\x38', '\n', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\a', '\t', '>', '\n', '\t', '\f', '\t', '\xE', 
		'\t', '\x41', '\v', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', 
		'K', '\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', 
		'V', '\n', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\a', 
		'\v', '\\', '\n', '\v', '\f', '\v', '\xE', '\v', '_', '\v', '\v', '\x3', 
		'\f', '\x3', '\f', '\x5', '\f', '\x63', '\n', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x6', '\r', 
		'k', '\n', '\r', '\r', '\r', '\xE', '\r', 'l', '\x3', '\r', '\x3', '\r', 
		'\x5', '\r', 'q', '\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x5', '\xE', '\x85', '\n', '\xE', '\x5', '\xE', '\x87', '\n', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\a', '\xE', '\xA9', '\n', '\xE', '\f', '\xE', 
		'\xE', '\xE', '\xAC', '\v', '\xE', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', 
		'\xB0', '\n', '\xE', '\f', '\xE', '\xE', '\xE', '\xB3', '\v', '\xE', '\x3', 
		'\xE', '\x2', '\x5', '\x10', '\x14', '\x1A', '\xF', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', 
		'\x2', '\x6', '\x3', '\x2', '\x1E', '\"', '\x3', '\x2', '\x16', '\x1D', 
		'\x3', '\x2', '\x12', '\x15', '\x3', '\x2', '#', '$', '\x2', '\xC5', '\x2', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x4', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\x6', ' ', '\x3', '\x2', '\x2', '\x2', '\b', '\"', '\x3', '\x2', 
		'\x2', '\x2', '\n', '$', '\x3', '\x2', '\x2', '\x2', '\f', '&', '\x3', 
		'\x2', '\x2', '\x2', '\xE', ',', '\x3', '\x2', '\x2', '\x2', '\x10', '\x37', 
		'\x3', '\x2', '\x2', '\x2', '\x12', 'J', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'U', '\x3', '\x2', '\x2', '\x2', '\x16', '\x62', '\x3', '\x2', '\x2', 
		'\x2', '\x18', 'p', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x1C', '\x1D', '\t', '\x2', '\x2', '\x2', '\x1D', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x1F', '\a', '\x1E', '\x2', 
		'\x2', '\x1F', '\x5', '\x3', '\x2', '\x2', '\x2', ' ', '!', '\t', '\x3', 
		'\x2', '\x2', '!', '\a', '\x3', '\x2', '\x2', '\x2', '\"', '#', '\t', 
		'\x4', '\x2', '\x2', '#', '\t', '\x3', '\x2', '\x2', '\x2', '$', '%', 
		'\a', '\x11', '\x2', '\x2', '%', '\v', '\x3', '\x2', '\x2', '\x2', '&', 
		'\'', '\t', '\x5', '\x2', '\x2', '\'', '\r', '\x3', '\x2', '\x2', '\x2', 
		'(', '-', '\x5', '\x2', '\x2', '\x2', ')', '-', '\x5', '\x6', '\x4', '\x2', 
		'*', '-', '\x5', '\b', '\x5', '\x2', '+', '-', '\x5', '\f', '\a', '\x2', 
		',', '(', '\x3', '\x2', '\x2', '\x2', ',', ')', '\x3', '\x2', '\x2', '\x2', 
		',', '*', '\x3', '\x2', '\x2', '\x2', ',', '+', '\x3', '\x2', '\x2', '\x2', 
		'-', '\xF', '\x3', '\x2', '\x2', '\x2', '.', '/', '\b', '\t', '\x1', '\x2', 
		'/', '\x38', '\x5', '\x1A', '\xE', '\x2', '\x30', '\x31', '\x5', '\x4', 
		'\x3', '\x2', '\x31', '\x32', '\x5', '\x10', '\t', '\x5', '\x32', '\x38', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\a', '\x3', '\x2', '\x2', 
		'\x34', '\x35', '\x5', '\x10', '\t', '\x2', '\x35', '\x36', '\a', '\x4', 
		'\x2', '\x2', '\x36', '\x38', '\x3', '\x2', '\x2', '\x2', '\x37', '.', 
		'\x3', '\x2', '\x2', '\x2', '\x37', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\x33', '\x3', '\x2', '\x2', '\x2', '\x38', '?', '\x3', '\x2', 
		'\x2', '\x2', '\x39', ':', '\f', '\x4', '\x2', '\x2', ':', ';', '\x5', 
		'\x2', '\x2', '\x2', ';', '<', '\x5', '\x10', '\t', '\x5', '<', '>', '\x3', 
		'\x2', '\x2', '\x2', '=', '\x39', '\x3', '\x2', '\x2', '\x2', '>', '\x41', 
		'\x3', '\x2', '\x2', '\x2', '?', '=', '\x3', '\x2', '\x2', '\x2', '?', 
		'@', '\x3', '\x2', '\x2', '\x2', '@', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x41', '?', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\x5', '\x10', 
		'\t', '\x2', '\x43', '\x44', '\x5', '\x6', '\x4', '\x2', '\x44', '\x45', 
		'\x5', '\x10', '\t', '\x2', '\x45', 'K', '\x3', '\x2', '\x2', '\x2', '\x46', 
		'G', '\a', '\x3', '\x2', '\x2', 'G', 'H', '\x5', '\x12', '\n', '\x2', 
		'H', 'I', '\a', '\x4', '\x2', '\x2', 'I', 'K', '\x3', '\x2', '\x2', '\x2', 
		'J', '\x42', '\x3', '\x2', '\x2', '\x2', 'J', '\x46', '\x3', '\x2', '\x2', 
		'\x2', 'K', '\x13', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\b', '\v', 
		'\x1', '\x2', 'M', 'V', '\x5', '\x12', '\n', '\x2', 'N', 'O', '\x5', '\n', 
		'\x6', '\x2', 'O', 'P', '\x5', '\x14', '\v', '\x4', 'P', 'V', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'R', '\a', '\x3', '\x2', '\x2', 'R', 'S', '\x5', '\x14', 
		'\v', '\x2', 'S', 'T', '\a', '\x4', '\x2', '\x2', 'T', 'V', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'L', '\x3', '\x2', '\x2', '\x2', 'U', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'Q', '\x3', '\x2', '\x2', '\x2', 'V', ']', '\x3', '\x2', 
		'\x2', '\x2', 'W', 'X', '\f', '\x5', '\x2', '\x2', 'X', 'Y', '\x5', '\b', 
		'\x5', '\x2', 'Y', 'Z', '\x5', '\x14', '\v', '\x6', 'Z', '\\', '\x3', 
		'\x2', '\x2', '\x2', '[', 'W', '\x3', '\x2', '\x2', '\x2', '\\', '_', 
		'\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', ']', 
		'^', '\x3', '\x2', '\x2', '\x2', '^', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'_', ']', '\x3', '\x2', '\x2', '\x2', '`', '\x63', '\a', '(', '\x2', '\x2', 
		'\x61', '\x63', '\a', '*', '\x2', '\x2', '\x62', '`', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x61', '\x3', '\x2', '\x2', '\x2', '\x63', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x64', 'q', '\x5', '\x16', '\f', '\x2', '\x65', 
		'q', '\a', ')', '\x2', '\x2', '\x66', 'g', '\a', '\x3', '\x2', '\x2', 
		'g', 'j', '\x5', '\x16', '\f', '\x2', 'h', 'i', '\a', '\x1F', '\x2', '\x2', 
		'i', 'k', '\x5', '\x16', '\f', '\x2', 'j', 'h', '\x3', '\x2', '\x2', '\x2', 
		'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 
		'l', 'm', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\a', '\x4', '\x2', '\x2', 'o', 'q', '\x3', '\x2', '\x2', '\x2', 
		'p', '\x64', '\x3', '\x2', '\x2', '\x2', 'p', '\x65', '\x3', '\x2', '\x2', 
		'\x2', 'p', '\x66', '\x3', '\x2', '\x2', '\x2', 'q', '\x19', '\x3', '\x2', 
		'\x2', '\x2', 'r', 's', '\b', '\xE', '\x1', '\x2', 's', '\x87', '\a', 
		'\x5', '\x2', '\x2', 't', '\x87', '\x5', '\x18', '\r', '\x2', 'u', '\x87', 
		'\a', '&', '\x2', '\x2', 'v', '\x87', '\a', '\'', '\x2', '\x2', 'w', '\x87', 
		'\a', '%', '\x2', '\x2', 'x', 'y', '\a', '\n', '\x2', '\x2', 'y', '\x87', 
		'\x5', '\x1A', '\xE', '\b', 'z', '{', '\a', '\x3', '\x2', '\x2', '{', 
		'|', '\x5', '\x1A', '\xE', '\x2', '|', '}', '\a', '\x4', '\x2', '\x2', 
		'}', '\x87', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\a', '\r', '\x2', 
		'\x2', '\x7F', '\x80', '\x5', '\x16', '\f', '\x2', '\x80', '\x81', '\a', 
		'\xE', '\x2', '\x2', '\x81', '\x84', '\x5', '\x1A', '\xE', '\x2', '\x82', 
		'\x83', '\a', '\xF', '\x2', '\x2', '\x83', '\x85', '\x5', '\x1A', '\xE', 
		'\x2', '\x84', '\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x87', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'r', '\x3', '\x2', '\x2', '\x2', '\x86', 't', '\x3', '\x2', '\x2', '\x2', 
		'\x86', 'u', '\x3', '\x2', '\x2', '\x2', '\x86', 'v', '\x3', '\x2', '\x2', 
		'\x2', '\x86', 'w', '\x3', '\x2', '\x2', '\x2', '\x86', 'x', '\x3', '\x2', 
		'\x2', '\x2', '\x86', 'z', '\x3', '\x2', '\x2', '\x2', '\x86', '~', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\xB1', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x89', '\f', '\x6', '\x2', '\x2', '\x89', '\x8A', '\a', '\f', '\x2', 
		'\x2', '\x8A', '\xB0', '\x5', '\x1A', '\xE', '\a', '\x8B', '\x8C', '\f', 
		'\x5', '\x2', '\x2', '\x8C', '\x8D', '\x5', '\xE', '\b', '\x2', '\x8D', 
		'\x8E', '\x5', '\x1A', '\xE', '\x6', '\x8E', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\f', '\f', '\x2', '\x2', '\x90', '\x91', '\a', 
		'\x6', '\x2', '\x2', '\x91', '\xB0', '\x5', '\x18', '\r', '\x2', '\x92', 
		'\x93', '\f', '\v', '\x2', '\x2', '\x93', '\x94', '\a', '\a', '\x2', '\x2', 
		'\x94', '\x95', '\x5', '\x14', '\v', '\x2', '\x95', '\x96', '\a', '\b', 
		'\x2', '\x2', '\x96', '\xB0', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', 
		'\f', '\n', '\x2', '\x2', '\x98', '\x99', '\a', '\a', '\x2', '\x2', '\x99', 
		'\x9A', '\x5', '\x10', '\t', '\x2', '\x9A', '\x9B', '\a', '\b', '\x2', 
		'\x2', '\x9B', '\xB0', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9D', '\f', 
		'\t', '\x2', '\x2', '\x9D', '\x9E', '\a', '\a', '\x2', '\x2', '\x9E', 
		'\x9F', '\x5', '\x10', '\t', '\x2', '\x9F', '\xA0', '\a', '\t', '\x2', 
		'\x2', '\xA0', '\xA1', '\x5', '\x10', '\t', '\x2', '\xA1', '\xA2', '\a', 
		'\b', '\x2', '\x2', '\xA2', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'\xA4', '\f', '\a', '\x2', '\x2', '\xA4', '\xA5', '\a', '\x3', '\x2', 
		'\x2', '\xA5', '\xAA', '\x5', '\x1A', '\xE', '\x2', '\xA6', '\xA7', '\a', 
		'\v', '\x2', '\x2', '\xA7', '\xA9', '\x5', '\x1A', '\xE', '\x2', '\xA8', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xAA', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\a', '\x4', '\x2', 
		'\x2', '\xAE', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xAF', '\x88', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\x8B', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\xAF', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\x97', '\x3', '\x2', '\x2', '\x2', '\xAF', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xAF', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB1', '\x3', '\x2', '\x2', '\x2', '\x10', 
		',', '\x37', '?', 'J', 'U', ']', '\x62', 'l', 'p', '\x84', '\x86', '\xAA', 
		'\xAF', '\xB1',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace BuildXL.Execution.Analyzer.JPath
