//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JPath.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BuildXL.Execution.Analyzer.JPath {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class JPathLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		WS=10, NOT=11, AND=12, OR=13, XOR=14, IFF=15, GTE=16, LTE=17, GT=18, LT=19, 
		EQ=20, NEQ=21, MATCH=22, NMATCH=23, MINUS=24, PLUS=25, TIMES=26, DIV=27, 
		MOD=28, IntLit=29, StrLit=30, RegExLit=31, VarID=32, FuncID=33, ESC_ID=34;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"WS", "NOT", "AND", "OR", "XOR", "IFF", "GTE", "LTE", "GT", "LT", "EQ", 
		"NEQ", "MATCH", "NMATCH", "MINUS", "PLUS", "TIMES", "DIV", "MOD", "IntLit", 
		"StrLit", "RegExLit", "IdFragment", "VarID", "FuncID", "ESC_ID"
	};


	public JPathLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public JPathLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'$'", "'.'", "'['", "']'", "'..'", "'|'", "','", 
		null, "'not'", "'and'", "'or'", "'xor'", "'iff'", "'>='", "'<='", "'>'", 
		"'<'", "'='", "'!='", "'~'", "'!~'", "'-'", "'+'", "'*'", "'/'", "'%'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "WS", "NOT", 
		"AND", "OR", "XOR", "IFF", "GTE", "LTE", "GT", "LT", "EQ", "NEQ", "MATCH", 
		"NMATCH", "MINUS", "PLUS", "TIMES", "DIV", "MOD", "IntLit", "StrLit", 
		"RegExLit", "VarID", "FuncID", "ESC_ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JPath.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static JPathLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '$', '\xCF', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x6', '\v', '^', '\n', '\v', '\r', '\v', '\xE', '\v', 
		'_', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1E', '\x6', '\x1E', '\x96', '\n', '\x1E', '\r', '\x1E', 
		'\xE', '\x1E', '\x97', '\x3', '\x1F', '\x3', '\x1F', '\a', '\x1F', '\x9C', 
		'\n', '\x1F', '\f', '\x1F', '\xE', '\x1F', '\x9F', '\v', '\x1F', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', '\x1F', '\a', '\x1F', '\xA4', '\n', '\x1F', 
		'\f', '\x1F', '\xE', '\x1F', '\xA7', '\v', '\x1F', '\x3', '\x1F', '\x5', 
		'\x1F', '\xAA', '\n', '\x1F', '\x3', ' ', '\x3', ' ', '\x6', ' ', '\xAE', 
		'\n', ' ', '\r', ' ', '\xE', ' ', '\xAF', '\x3', ' ', '\x3', ' ', '\x3', 
		' ', '\x6', ' ', '\xB5', '\n', ' ', '\r', ' ', '\xE', ' ', '\xB6', '\x3', 
		' ', '\x5', ' ', '\xBA', '\n', ' ', '\x3', '!', '\x3', '!', '\a', '!', 
		'\xBE', '\n', '!', '\f', '!', '\xE', '!', '\xC1', '\v', '!', '\x3', '\"', 
		'\x3', '\"', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', '$', '\x3', '$', 
		'\x6', '$', '\xCA', '\n', '$', '\r', '$', '\xE', '$', '\xCB', '\x3', '$', 
		'\x3', '$', '\x2', '\x2', '%', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', 
		')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', 
		'\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', 
		' ', '?', '!', '\x41', '\x2', '\x43', '\"', '\x45', '#', 'G', '$', '\x3', 
		'\x2', '\v', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x3', 
		'\x2', '\x32', ';', '\x3', '\x2', ')', ')', '\x3', '\x2', '$', '$', '\x3', 
		'\x2', '\x31', '\x31', '\x3', '\x2', '#', '#', '\x4', '\x2', '\x43', '\\', 
		'\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x3', '\x2', '\x62', '\x62', '\x2', '\xD7', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', 
		';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 'G', '\x3', '\x2', 
		'\x2', '\x2', '\x3', 'I', '\x3', '\x2', '\x2', '\x2', '\x5', 'K', '\x3', 
		'\x2', '\x2', '\x2', '\a', 'M', '\x3', '\x2', '\x2', '\x2', '\t', 'O', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'Q', '\x3', '\x2', '\x2', '\x2', '\r', 
		'S', '\x3', '\x2', '\x2', '\x2', '\xF', 'U', '\x3', '\x2', '\x2', '\x2', 
		'\x11', 'X', '\x3', '\x2', '\x2', '\x2', '\x13', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\x15', ']', '\x3', '\x2', '\x2', '\x2', '\x17', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x19', 'g', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'k', '\x3', '\x2', '\x2', '\x2', '\x1D', 'n', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', 'r', '\x3', '\x2', '\x2', '\x2', '!', 'v', '\x3', '\x2', '\x2', 
		'\x2', '#', 'y', '\x3', '\x2', '\x2', '\x2', '%', '|', '\x3', '\x2', '\x2', 
		'\x2', '\'', '~', '\x3', '\x2', '\x2', '\x2', ')', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '+', '\x82', '\x3', '\x2', '\x2', '\x2', '-', '\x85', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x87', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x33', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x37', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\x92', '\x3', '\x2', '\x2', '\x2', ';', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '=', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '?', '\xB9', '\x3', '\x2', '\x2', '\x2', '\x41', '\xBB', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\xC2', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\xC4', '\x3', '\x2', '\x2', '\x2', 'G', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'J', '\a', '*', '\x2', '\x2', 'J', '\x4', '\x3', '\x2', '\x2', 
		'\x2', 'K', 'L', '\a', '+', '\x2', '\x2', 'L', '\x6', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'N', '\a', '&', '\x2', '\x2', 'N', '\b', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'P', '\a', '\x30', '\x2', '\x2', 'P', '\n', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'R', '\a', ']', '\x2', '\x2', 'R', '\f', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'T', '\a', '_', '\x2', '\x2', 'T', '\xE', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'V', '\a', '\x30', '\x2', '\x2', 'V', 'W', '\a', '\x30', 
		'\x2', '\x2', 'W', '\x10', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\a', 
		'~', '\x2', '\x2', 'Y', '\x12', '\x3', '\x2', '\x2', '\x2', 'Z', '[', 
		'\a', '.', '\x2', '\x2', '[', '\x14', '\x3', '\x2', '\x2', '\x2', '\\', 
		'^', '\t', '\x2', '\x2', '\x2', ']', '\\', '\x3', '\x2', '\x2', '\x2', 
		'^', '_', '\x3', '\x2', '\x2', '\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', 
		'_', '`', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x61', '\x62', '\b', '\v', '\x2', '\x2', '\x62', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x63', '\x64', '\a', 'p', '\x2', '\x2', '\x64', 
		'\x65', '\a', 'q', '\x2', '\x2', '\x65', '\x66', '\a', 'v', '\x2', '\x2', 
		'\x66', '\x18', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '\x63', '\x2', 
		'\x2', 'h', 'i', '\a', 'p', '\x2', '\x2', 'i', 'j', '\a', '\x66', '\x2', 
		'\x2', 'j', '\x1A', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', 'q', '\x2', 
		'\x2', 'l', 'm', '\a', 't', '\x2', '\x2', 'm', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'n', 'o', '\a', 'z', '\x2', '\x2', 'o', 'p', '\a', 'q', '\x2', 
		'\x2', 'p', 'q', '\a', 't', '\x2', '\x2', 'q', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', 'r', 's', '\a', 'k', '\x2', '\x2', 's', 't', '\a', 'h', '\x2', 
		'\x2', 't', 'u', '\a', 'h', '\x2', '\x2', 'u', ' ', '\x3', '\x2', '\x2', 
		'\x2', 'v', 'w', '\a', '@', '\x2', '\x2', 'w', 'x', '\a', '?', '\x2', 
		'\x2', 'x', '\"', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', '>', '\x2', 
		'\x2', 'z', '{', '\a', '?', '\x2', '\x2', '{', '$', '\x3', '\x2', '\x2', 
		'\x2', '|', '}', '\a', '@', '\x2', '\x2', '}', '&', '\x3', '\x2', '\x2', 
		'\x2', '~', '\x7F', '\a', '>', '\x2', '\x2', '\x7F', '(', '\x3', '\x2', 
		'\x2', '\x2', '\x80', '\x81', '\a', '?', '\x2', '\x2', '\x81', '*', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x83', '\a', '#', '\x2', '\x2', '\x83', 
		'\x84', '\a', '?', '\x2', '\x2', '\x84', ',', '\x3', '\x2', '\x2', '\x2', 
		'\x85', '\x86', '\a', '\x80', '\x2', '\x2', '\x86', '.', '\x3', '\x2', 
		'\x2', '\x2', '\x87', '\x88', '\a', '#', '\x2', '\x2', '\x88', '\x89', 
		'\a', '\x80', '\x2', '\x2', '\x89', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\x8A', '\x8B', '\a', '/', '\x2', '\x2', '\x8B', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\x8C', '\x8D', '\a', '-', '\x2', '\x2', '\x8D', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', ',', '\x2', '\x2', '\x8F', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\a', '\x31', '\x2', 
		'\x2', '\x91', '\x38', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\a', 
		'\'', '\x2', '\x2', '\x93', ':', '\x3', '\x2', '\x2', '\x2', '\x94', '\x96', 
		'\t', '\x3', '\x2', '\x2', '\x95', '\x94', '\x3', '\x2', '\x2', '\x2', 
		'\x96', '\x97', '\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', '\x2', 
		'\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', '\x2', '\x98', '<', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '\x9D', '\a', ')', '\x2', '\x2', '\x9A', 
		'\x9C', '\n', '\x4', '\x2', '\x2', '\x9B', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xAA', '\a', ')', '\x2', '\x2', '\xA1', '\xA5', '\a', 
		'$', '\x2', '\x2', '\xA2', '\xA4', '\n', '\x5', '\x2', '\x2', '\xA3', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA7', '\x3', '\x2', '\x2', 
		'\x2', '\xA5', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'\xA5', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xAA', '\a', '$', '\x2', 
		'\x2', '\xA9', '\x99', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xA1', '\x3', 
		'\x2', '\x2', '\x2', '\xAA', '>', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xAD', '\a', '\x31', '\x2', '\x2', '\xAC', '\xAE', '\n', '\x6', '\x2', 
		'\x2', '\xAD', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xBA', '\a', '\x31', '\x2', '\x2', '\xB2', '\xB4', '\a', 
		'#', '\x2', '\x2', '\xB3', '\xB5', '\n', '\a', '\x2', '\x2', '\xB4', '\xB3', 
		'\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\x3', '\x2', '\x2', '\x2', 
		'\xB6', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', '\x2', 
		'\x2', '\x2', '\xB7', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xBA', 
		'\a', '#', '\x2', '\x2', '\xB9', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', '\xBA', '@', '\x3', '\x2', '\x2', 
		'\x2', '\xBB', '\xBF', '\t', '\b', '\x2', '\x2', '\xBC', '\xBE', '\t', 
		'\t', '\x2', '\x2', '\xBD', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\xC1', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\xBF', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC0', '\x42', '\x3', 
		'\x2', '\x2', '\x2', '\xC1', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC2', 
		'\xC3', '\x5', '\x41', '!', '\x2', '\xC3', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\xC4', '\xC5', '\a', '&', '\x2', '\x2', '\xC5', '\xC6', '\x5', 
		'\x41', '!', '\x2', '\xC6', '\x46', '\x3', '\x2', '\x2', '\x2', '\xC7', 
		'\xC9', '\a', '\x62', '\x2', '\x2', '\xC8', '\xCA', '\n', '\n', '\x2', 
		'\x2', '\xC9', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xCB', 
		'\xCC', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', '\x3', '\x2', '\x2', 
		'\x2', '\xCD', '\xCE', '\a', '\x62', '\x2', '\x2', '\xCE', 'H', '\x3', 
		'\x2', '\x2', '\x2', '\r', '\x2', '_', '\x97', '\x9D', '\xA5', '\xA9', 
		'\xAF', '\xB6', '\xB9', '\xBF', '\xCB', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace BuildXL.Execution.Analyzer.JPath
